from django . urls import path
from . import views
urlpatterns=[
    path('display_Batch/',views.display_Batch,name='display_Batch'),
    path('display_Paper/',views.display_Paper,name='display_Paper'),
    path('display_Student/',views.display_Student,name='display_Student'),
    path('display_StudentTrans/',views.display_StudentTrans,name='display_StudentTrans'),
    path('display_Course/',views.display_Course,name='display_Course'),
    path('display_Exam/',views.display_Exam,name='display_Exam'),
    path('display_Sem/',views.display_Sem,name='display_Sem'),
    path('process_batch_entry/',views.process_batch_entry,name='process_batch_entry'),
    path('Batch_view/',views.Batch_view,name='Batch_view'),
    path('displayBatchInput/',views.displayBatchInput,name='displayBatchInput'),
    path('display_image/',views.display_image,name='display_image'),
    path('Course_view/',views.Course_view,name='Course_view'),
    path('process_course_entry/',views.process_course_entry,name='process_course_entry'),
    path('displayCourseInput/',views.displayCourseInput,name='displayCourseInput'),
    path('process_exam_entry/',views.process_exam_entry,name='process_exam_entry'),
    path('Exam_view/',views.Exam_view,name='Exam_view'),
    path('displayExamInput/',views.displayExamInput,name='displayExamInput'),
    path('process_paper_entry/',views.process_paper_entry,name='process_paper_entry'),
    path('Paper_view/',views.Paper_view,name='Paper_view'),
    path('displayPaperInput/',views.displayPaperInput,name='displayPaperInput'),
    path('process_sem_entry/',views.process_sem_entry,name='process_sem_entry'),
    path('Sem_view/',views.Sem_view,name='Sem_view'),
    path('displaySemInput/',views.displaySemInput,name='displaySemInput'),
    path('Student_view/',views.Student_view,name='Student_view'),
    path('displayStudentInput/',views.displayStudentInput,name='displayStudentInput'),
    path('process_student_entry/',views.process_student_entry,name='process_student_entry'),
    path('delete/<pk>/',views.delete,name='delete'),
    path('delete_Batch/',views.delete_Batch,name='delete_Batch'),
    path('delete1/<pk>/',views.delete1,name='delete1'),
    path('delete_Course/',views.delete_Course,name='delete_Course'),
    path('delete2/<pk>/',views.delete2,name='delete2'),
    path('delete_Paper/',views.delete_Paper,name='delete_Paper'),
    path('delete3/<pk>/',views.delete3,name='delete3'),
    path('delete_Exam',views.delete_Exam,name='delete_Exam'),
    path('delete4/<pk>/',views.delete4,name='delete4'),
    path('delete_Sem/',views.delete_Sem,name='delete_Sem'),
    path('search/', views.search_view, name='search'),
    path('search1/',views.search_view1,name='search1'),
    path('search2/',views.search_view2,name='search2'),
    path('search3/',views.search_view3,name='search3'),
    path('search4/',views.search_view4,name='search4'),
    
    path('edit/<int:batch_id>/', views.edit_batch, name='edit_batch'),
    path('batch/<int:batch_id>/', views.batch_detail, name='batch_detail'),
    path('batch_all_details/',views.batch_all_details,name='batch_all_details'),

    path('print_Batch/',views.print_Batch,name='print_Batch'),

    path('edit1/<int:course_id>/', views.edit_course, name='edit_course'),
    path('course/<int:course_id>/', views.course_detail,name='course_detail'),
    path('course_all_details/',views.course_all_details,name='course_all_details'),

    path('edit2/<int:paper_id>/',views.edit_paper,name='edit_paper'),
    path('paper/<int:paper_id>/',views.paper_detail,name='paper_detail'),
    path('paper_all_details/',views.paper_all_details,name='paper_all_details'),
    
    path('edit3/<int:exam_id>/',views.edit_exam,name='edit_exam'),
    path('exam/<int:exam_id>/',views.exam_detail,name='exam_detail'),
    path('exam_all_details/',views.exam_all_details,name='exam_all_details'),

    path('edit4/<int:sem_id>/',views.edit_sem,name='edit_sem'),
    path('sem/<int:sem_id>/',views.sem_detail,name='sem_detail'),
    path('sem_all_details/',views.sem_all_details,name='sem_all_details'),
]

