# Generated by Django 5.0.6 on 2024-07-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmaster',
            name='batchId',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='batchmaster',
            name='batchNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='papermaster',
            name='paperName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='papermaster',
            name='papertype',
            field=models.CharField(max_length=30),
        ),
    ]
