# Generated by Django 5.0.6 on 2024-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_batchmaster_batchid_alter_batchmaster_batchno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmaster',
            name='batchId',
            field=models.CharField(max_length=15),
        ),
    ]
